apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: my-app-web:1.0
        ports:
        - containerPort: 3000
        imagePullPolicy: Never
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        - name: API_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: api_message_key
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: secret_api_key
